### ISSUE TITLE
[bug] Update mirmir if prometheusRule is updated after initial creation

### ISSUE THREAD

**Issue by nissessenap** [AmiditeX/mimir-operator#5]
So I haven't had time trying this out, but I have read the code and I don't think this is done.

What happens if you remove a prometheusRule that you previously have synced to mirmir?
I think that you won't trigger a delete in mimir.
 
To solve this I think we need to start to watch prometheusRule as well in the reconciler else you won't see if a new prometheusRule gets created after you create the initial MimirTenant CR, same thing goes for delete.
When a prometheusRule is created matches the selector you have defined in MimirTenant we need to add a finaliazer to it. When a delete of that same CR happens, we have to trigger a readread of all the rules and upload it again using mirmirtool.

This is a similar way https://github.com/giantswarm/starboard-exporter works.

I might be totally wrong, and I haven't had the time to try anything around this, but this is my current understanding of the code. If I'm wrong, please say so :)

I will try to get time to verify this.

**Comment by eiTi3Aishieg** [comment]
You're not wrong at all, I'm not handling that case. I'm not sure about adding a finalizer to the PrometheusRules tho.
It would make the imported CRs "part" of the operator by somewhat taking ownership of their lifecycle.

The reconciliation loop would end up cleaning up any deleted rule anyway right? And if we're watching for those resources, we can delete them in real time.

**Comment by eiTi3Aishieg** [comment]
The reconciliation is now ran whenever a PrometheusRule is changed on the cluster. To minimize the number of reloads, we need to implement  #12.
